In [1]:
import requests

headers = {
    'accept': 'application/json',
    'Authorization': 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg==',
}

params = (
    ('page', '1'),
    ('perPage', '1000'),
    ('serviceKey', 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg=='),
)

## decode key가 적용되었음.
## api마다 연결이 되지 않는다고 한다면, encode, decode를 바꾸어 테스트해볼 것.
response = requests.get('https://api.odcloud.kr/api/15069309/v1/uddi:973ad0df-617a-4565-8e82-8ea7869e75d4', headers=headers, params=params)
response

In [2]:
json_total = response.json()
json_total

{'currentCount': 1000,
 'data': [{'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '당직자공용 기자',
   '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '황재희',
   '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200201134957462',
   '일자': '2020-02-01',
   '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001',
   '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이미경(capital);',
   '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국경제',
   '원본주소': 'https://www.hankyung.com/society/article/2020020121817',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002',
   '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김봄이',
   '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020109431879372',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이정환2 기자',
   '본문': '[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000068',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=103663&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001',
   '키워드': '신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,속보,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '전동혁',
   '본문': '◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': 'MBC',
   '원본주소': 'https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html',
   '일자': '2020-02-01',
   '제목': "2차·3차 감염에도 '슈퍼 전파자'는 없다?",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001',
   '키워드': '2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020109535883286',
   '일자': '2020-02-01',
   '제목': "[속보] '신종 코로나' 환자 1명 추가…모두 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001',
   '키워드': '신종,코로나,추가,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': None,
   '본문': "'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국일보',
   '원본주소': None,
   '일자': '2020-02-02',
   '제목': "[속보] '신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001',
   '키워드': '감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나바이러스,감염증,추가,신종,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '배성훈',
   '본문': "'신종코로나' 확진환자 3명 추가…국내 총 15명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020209591605175',
   '일자': '2020-02-02',
   '제목': "[속보] '신종코로나' 확진환자 3명 추가…국내 총 15명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200202100031001',
   '키워드': '신종코,추가,확진,환자,15명,신종코,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이종호 기자',
   '본문': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중”',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYS34Z0O3',
   '일자': '2020-02-03',
   '제목': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중 (속보)',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203140915001',
   '키워드': '질본,913명,모니터링,속보,질본,913명,모니터링',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '질본,코로나,접촉자,환자,모니터링,속보,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020314022654591',
   '일자': '2020-02-03',
   '제목': '[속보] 신종 코로나 추가 확진환자 없어…총 15명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203140309001',
   '키워드': '신종,코로,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,추가,환자,확진,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 2번 환자 유전자증폭검사, 증상 모두 완쾌...퇴원 검토',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYS2DNUZ9',
   '일자': '2020-02-03',
   '제목': '[속보] 신종 코로나 2번 환자 유전자증폭검사 음성, 증상 완쾌...퇴원 검토 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203144537001',
   '키워드': '신종,코로나,환자,유전자,증폭,검사,음성,증상,완쾌,퇴원,검토,속보,유전자증폭검사,환자,유전자,증폭,검사,증상,완쾌,퇴원,검토',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,유전자증폭검사,유전자,음성,환자,증상,검사,퇴원,검토,완쾌,증폭,속보,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020314113030951',
   '일자': '2020-02-03',
   '제목': "[속보] '신종 코로나' 환자 접촉자 총 913명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203141149001',
   '키워드': '신종,코로나,환자,접촉자,913명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,접촉자,환자,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '문혜원',
   '본문': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제  문혜원 기자 hmoon3',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020316544660519',
   '일자': '2020-02-03',
   '제목': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203165715001',
   '키워드': '신종,코로,환자,접촉자,이날,감시,해제,속보,신종,코로,환자,접촉자,이날,감시,해제',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,코로,이날,환자,해제,감시,신종,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014198768&code=61121111&cp=kd',
   '일자': '2020-02-04',
   '제목': '[속보]신종 코로나 1명 추가 확진…총 16명 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200204110332001',
   '키워드': '신종,코로,확진,추가,발생,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,추가,환자,발생,확진,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '정종훈(sakehoon)',
   '본문': '[속보] 신종 코로나 기존 환자 15명 상태 안정적',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '중앙일보',
   '원본주소': 'https://news.joins.com/article/olink/23291997',
   '일자': '2020-02-04',
   '제목': '[속보] 신종 코로나 기존 환자 15명 상태 안정적',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100901.20200204135652001',
   '키워드': '신종,코로,환자,상태,안정적,속보,신종,코로,환자,상태,안정적',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,환자,안정적,상태,신종,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '류영상',
   '본문': '[디지털뉴스국 류영상 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=112550&year=2020',
   '일자': '2020-02-04',
   '제목': '[속보] `신종코로나` 16번째 확진환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200204110312001',
   '키워드': '신종코,16번,확진,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '16번,신종코,발생,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '황재희',
   '본문': '[사진=연합뉴스]  신종 코로나바이러스 감염증 확진자가 4일 1명이 추가돼 총 16명으로 늘어났다. 이들과 접촉한 사람은 총 1318명으로 확인됐다. 현재 확진 여부 검사를 실시 중인 사람은 129명이다.   황재희 기자 jhhwang',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200204135428479',
   '일자': '2020-02-04',
   '제목': '[속보] 신종 코로나 확진자 16명 접촉자 1318명…129명 검사 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200204135754001',
   '키워드': '신종,코로,확진자,접촉자,129명,검사,신종,코로나바이러스,감염증,확진자,추가,16명,접촉,사람,1318명,확인,검사,확진,여부,사람,129명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,접촉자,코로나바이러스,감염증,코로,신종,사람,검사,확진,여부,추가,확인,접촉'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': None,
   '본문': '전 세계를 공포로 몰아넣고 있는 신종 코로나바이러스 감염증(신종 코로나). 무증상 상태에서도 감염이 발생할 수 있는 것으로 알려져 공포심이 더욱 커지고 있다. 국내에서도 빠르게 확진자가 증가하고 있는 가운데 신종 코로나 예방법은 무엇인지 자세히 알아본다.',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '동아일보',
   '원본주소': 'http://www.donga.com/news/article/all/20200204/99522244/1',
   '일자': '2020-02-04',
   '제목': '[오늘의 채널A]신종 코로나 예방법',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100401.20200204030254003',
   '키워드': '신종,코로,예방법,행복,4일,8시,세계,공포,감염증,신종,코로나바이러스,신종,코로나,상태,감염,발생,공포심,확진자,증가,코로,신종,예방법',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '예방법,코로,공포심,확진자,코로나,코로나바이러스,감염증,신종,상태,발생,증가,세계,감염,행복,공포'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '홍지예',
   '본문': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '중부일보',
   '원본주소': 'www.joongboo.com/news/articleView.html?idxno=363397074',
   '일자': '2020-02-05',
   '제목': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01400501.20200205092214001',
   '키워드': '신종,코로나,추가,확진,환자,18명,속보,신종,코로나,추가,확진,환자,18명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,추가,속보,환자,신종,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '유현석',
   '본문': '[아시아경제 유현석 기자]  유현석 기자 guspower',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020519453821856',
   '일자': '2020-02-05',
   '제목': "[속보]'신종 코로나' 19번째 국내 확진환자 발생",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200205194643001',
   '키워드': '신종,코로나,19번,발생,확진,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,19번,발생,확진,신종,환자'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': '[디지털뉴스국 이상규 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=117428&year=2020',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 검사 하루 160여건…7일부터 2000건 가능해져',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200205111530001',
   '키워드': '신종,코로나,검사,하루,7일,가능',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,검사,하루,가능,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김민호',
   '본문': '자세한 내용 이어집니다 김민호 기자 kmh',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국일보',
   '원본주소': None,
   '일자': '2020-02-05',
   '제목': '[속보] 신종 코로나, 국내 19번째 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200205050514001',
   '키워드': '신종,코로나,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,발생'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '정현용',
   '본문': '신종코로나 19번째 확진환자 발생 정현용 기자 junghy77',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울신문',
   '원본주소': 'http://www.seoul.co.kr/news/newsView.php?id=20200205500168',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 19번째 확진환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100611.20200205194759001',
   '키워드': '신종코로,19번,확진,환자,발생,신종코로,19번,확진,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,19번,신종코로,발생,신종,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김봄이',
   '본문': "'신종코로나' 확진환자 2명 추가…확진자 18명으로 늘어",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020509232224944',
   '일자': '2020-02-05',
   '제목': "[속보] '신종코로나' 확진자 2명 추가…국내 총 18명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200205092434001',
   '키워드': '신종코,추가,확진자,18명,신종코,추가,확진,환자,확진자,18명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,신종코,추가,확진,환자'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014205933&code=61121111&cp=kd',
   '일자': '2020-02-05',
   '제목': '[속보]신종 코로나 환자 1명 추가 발생…총 19명 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205194340001',
   '키워드': '신종,코로,환자,추가,발생,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,환자,발생,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014203265&code=61121111&cp=kd',
   '일자': '2020-02-05',
   '제목': '[속보]신종 코로나 확진자 2명 추가…총 18명 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205110206002',
   '키워드': '신종,코로,추가,확진자,발생,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,코로,환자,발생,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '송종호',
   '본문': '[사진=연합뉴스 제공]   신종코로나 2번 환자 오늘 퇴원 송종호 기자 sunshine',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200205133702465',
   '일자': '2020-02-05',
   '제목': '[?속보] 신종코로나 2번 환자 오늘 퇴원',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200205134343001',
   '키워드': '환자,퇴원,신종,코로나,환자,환자,퇴원,신종,코로나,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,퇴원'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 신종코로나 2번 환자 오늘 퇴원',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYSZEKHH6',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 2번 환자 오늘 퇴원',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205133301001',
   '키워드': '환자,퇴원,신종,코로나,환자,속보,환자,퇴원,신종,코로나,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,퇴원,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYSZAF0RM',
   '일자': '2020-02-05',
   '제목': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205110416001',
   '키워드': '신종,코로,160명,하루,진단,가능,환자,속보,신종,코로,160명,하루,진단,가능,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,하루,환자,신종,속보,가능,진단'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 첫번재 환자 상태 호전으로 퇴원',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,

In [3]:
import pickle
with open('covid-data-gokr.json', 'wb') as fp:
    pickle.dump(json_total, fp)

In [4]:
with open('covid-data-gokr.json', 'rb') as fp:
    json_data = pickle.load(fp)
json_data

{'currentCount': 1000,
 'data': [{'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '당직자공용 기자',
   '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '황재희',
   '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200201134957462',
   '일자': '2020-02-01',
   '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001',
   '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이미경(capital);',
   '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국경제',
   '원본주소': 'https://www.hankyung.com/society/article/2020020121817',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002',
   '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김봄이',
   '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020109431879372',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이정환2 기자',
   '본문': '[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000068',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=103663&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001',
   '키워드': '신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,속보,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '전동혁',
   '본문': '◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': 'MBC',
   '원본주소': 'https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html',
   '일자': '2020-02-01',
   '제목': "2차·3차 감염에도 '슈퍼 전파자'는 없다?",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001',
   '키워드': '2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020109535883286',
   '일자': '2020-02-01',
   '제목': "[속보] '신종 코로나' 환자 1명 추가…모두 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001',
   '키워드': '신종,코로나,추가,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': None,
   '본문': "'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국일보',
   '원본주소': None,
   '일자': '2020-02-02',
   '제목': "[속보] '신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001',
   '키워드': '감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나바이러스,감염증,추가,신종,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '배성훈',
   '본문': "'신종코로나' 확진환자 3명 추가…국내 총 15명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020209591605175',
   '일자': '2020-02-02',
   '제목': "[속보] '신종코로나' 확진환자 3명 추가…국내 총 15명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200202100031001',
   '키워드': '신종코,추가,확진,환자,15명,신종코,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이종호 기자',
   '본문': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중”',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYS34Z0O3',
   '일자': '2020-02-03',
   '제목': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중 (속보)',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203140915001',
   '키워드': '질본,913명,모니터링,속보,질본,913명,모니터링',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '질본,코로나,접촉자,환자,모니터링,속보,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020314022654591',
   '일자': '2020-02-03',
   '제목': '[속보] 신종 코로나 추가 확진환자 없어…총 15명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203140309001',
   '키워드': '신종,코로,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,추가,환자,확진,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 2번 환자 유전자증폭검사, 증상 모두 완쾌...퇴원 검토',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYS2DNUZ9',
   '일자': '2020-02-03',
   '제목': '[속보] 신종 코로나 2번 환자 유전자증폭검사 음성, 증상 완쾌...퇴원 검토 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203144537001',
   '키워드': '신종,코로나,환자,유전자,증폭,검사,음성,증상,완쾌,퇴원,검토,속보,유전자증폭검사,환자,유전자,증폭,검사,증상,완쾌,퇴원,검토',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,유전자증폭검사,유전자,음성,환자,증상,검사,퇴원,검토,완쾌,증폭,속보,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020314113030951',
   '일자': '2020-02-03',
   '제목': "[속보] '신종 코로나' 환자 접촉자 총 913명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203141149001',
   '키워드': '신종,코로나,환자,접촉자,913명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,접촉자,환자,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '문혜원',
   '본문': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제  문혜원 기자 hmoon3',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020316544660519',
   '일자': '2020-02-03',
   '제목': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203165715001',
   '키워드': '신종,코로,환자,접촉자,이날,감시,해제,속보,신종,코로,환자,접촉자,이날,감시,해제',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,코로,이날,환자,해제,감시,신종,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014198768&code=61121111&cp=kd',
   '일자': '2020-02-04',
   '제목': '[속보]신종 코로나 1명 추가 확진…총 16명 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200204110332001',
   '키워드': '신종,코로,확진,추가,발생,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,추가,환자,발생,확진,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '정종훈(sakehoon)',
   '본문': '[속보] 신종 코로나 기존 환자 15명 상태 안정적',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '중앙일보',
   '원본주소': 'https://news.joins.com/article/olink/23291997',
   '일자': '2020-02-04',
   '제목': '[속보] 신종 코로나 기존 환자 15명 상태 안정적',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100901.20200204135652001',
   '키워드': '신종,코로,환자,상태,안정적,속보,신종,코로,환자,상태,안정적',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,환자,안정적,상태,신종,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '류영상',
   '본문': '[디지털뉴스국 류영상 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=112550&year=2020',
   '일자': '2020-02-04',
   '제목': '[속보] `신종코로나` 16번째 확진환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200204110312001',
   '키워드': '신종코,16번,확진,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '16번,신종코,발생,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '황재희',
   '본문': '[사진=연합뉴스]  신종 코로나바이러스 감염증 확진자가 4일 1명이 추가돼 총 16명으로 늘어났다. 이들과 접촉한 사람은 총 1318명으로 확인됐다. 현재 확진 여부 검사를 실시 중인 사람은 129명이다.   황재희 기자 jhhwang',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200204135428479',
   '일자': '2020-02-04',
   '제목': '[속보] 신종 코로나 확진자 16명 접촉자 1318명…129명 검사 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200204135754001',
   '키워드': '신종,코로,확진자,접촉자,129명,검사,신종,코로나바이러스,감염증,확진자,추가,16명,접촉,사람,1318명,확인,검사,확진,여부,사람,129명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,접촉자,코로나바이러스,감염증,코로,신종,사람,검사,확진,여부,추가,확인,접촉'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': None,
   '본문': '전 세계를 공포로 몰아넣고 있는 신종 코로나바이러스 감염증(신종 코로나). 무증상 상태에서도 감염이 발생할 수 있는 것으로 알려져 공포심이 더욱 커지고 있다. 국내에서도 빠르게 확진자가 증가하고 있는 가운데 신종 코로나 예방법은 무엇인지 자세히 알아본다.',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '동아일보',
   '원본주소': 'http://www.donga.com/news/article/all/20200204/99522244/1',
   '일자': '2020-02-04',
   '제목': '[오늘의 채널A]신종 코로나 예방법',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100401.20200204030254003',
   '키워드': '신종,코로,예방법,행복,4일,8시,세계,공포,감염증,신종,코로나바이러스,신종,코로나,상태,감염,발생,공포심,확진자,증가,코로,신종,예방법',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '예방법,코로,공포심,확진자,코로나,코로나바이러스,감염증,신종,상태,발생,증가,세계,감염,행복,공포'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '홍지예',
   '본문': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '중부일보',
   '원본주소': 'www.joongboo.com/news/articleView.html?idxno=363397074',
   '일자': '2020-02-05',
   '제목': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01400501.20200205092214001',
   '키워드': '신종,코로나,추가,확진,환자,18명,속보,신종,코로나,추가,확진,환자,18명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,추가,속보,환자,신종,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '유현석',
   '본문': '[아시아경제 유현석 기자]  유현석 기자 guspower',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020519453821856',
   '일자': '2020-02-05',
   '제목': "[속보]'신종 코로나' 19번째 국내 확진환자 발생",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200205194643001',
   '키워드': '신종,코로나,19번,발생,확진,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,19번,발생,확진,신종,환자'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': '[디지털뉴스국 이상규 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=117428&year=2020',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 검사 하루 160여건…7일부터 2000건 가능해져',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200205111530001',
   '키워드': '신종,코로나,검사,하루,7일,가능',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,검사,하루,가능,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김민호',
   '본문': '자세한 내용 이어집니다 김민호 기자 kmh',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국일보',
   '원본주소': None,
   '일자': '2020-02-05',
   '제목': '[속보] 신종 코로나, 국내 19번째 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200205050514001',
   '키워드': '신종,코로나,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,발생'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '정현용',
   '본문': '신종코로나 19번째 확진환자 발생 정현용 기자 junghy77',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울신문',
   '원본주소': 'http://www.seoul.co.kr/news/newsView.php?id=20200205500168',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 19번째 확진환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100611.20200205194759001',
   '키워드': '신종코로,19번,확진,환자,발생,신종코로,19번,확진,환자,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,19번,신종코로,발생,신종,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김봄이',
   '본문': "'신종코로나' 확진환자 2명 추가…확진자 18명으로 늘어",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020509232224944',
   '일자': '2020-02-05',
   '제목': "[속보] '신종코로나' 확진자 2명 추가…국내 총 18명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200205092434001',
   '키워드': '신종코,추가,확진자,18명,신종코,추가,확진,환자,확진자,18명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,신종코,추가,확진,환자'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014205933&code=61121111&cp=kd',
   '일자': '2020-02-05',
   '제목': '[속보]신종 코로나 환자 1명 추가 발생…총 19명 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205194340001',
   '키워드': '신종,코로,환자,추가,발생,발생',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,환자,발생,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김영선 기자',
   '본문': '김영선 기자 ys8584',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '국민일보',
   '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014203265&code=61121111&cp=kd',
   '일자': '2020-02-05',
   '제목': '[속보]신종 코로나 확진자 2명 추가…총 18명 환자 발생',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205110206002',
   '키워드': '신종,코로,추가,확진자,발생,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,코로,환자,발생,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '송종호',
   '본문': '[사진=연합뉴스 제공]   신종코로나 2번 환자 오늘 퇴원 송종호 기자 sunshine',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200205133702465',
   '일자': '2020-02-05',
   '제목': '[?속보] 신종코로나 2번 환자 오늘 퇴원',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200205134343001',
   '키워드': '환자,퇴원,신종,코로나,환자,환자,퇴원,신종,코로나,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,퇴원'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 신종코로나 2번 환자 오늘 퇴원',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYSZEKHH6',
   '일자': '2020-02-05',
   '제목': '[속보] 신종코로나 2번 환자 오늘 퇴원',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205133301001',
   '키워드': '환자,퇴원,신종,코로나,환자,속보,환자,퇴원,신종,코로나,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,신종,퇴원,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '서울경제',
   '원본주소': 'http://www.sedaily.com/NewsView/1YYSZAF0RM',
   '일자': '2020-02-05',
   '제목': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205110416001',
   '키워드': '신종,코로,160명,하루,진단,가능,환자,속보,신종,코로,160명,하루,진단,가능,환자',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로,하루,환자,신종,속보,가능,진단'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '우영탁 기자',
   '본문': '[속보] 첫번재 환자 상태 호전으로 퇴원',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,

In [5]:
data = json_data['data']
data[:5]

[{'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '당직자공용 기자',
  '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '헤럴드경제',
  '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이상규',
  '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일경제',
  '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '일자': '2020-02-01',
  '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
  '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '접촉자,신종코,감시,확진,검사,속보'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '황재희',
  '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '아주경제',
  '원본주소': 'http://www.ajunews.com/view/20200201134957462',
  '일자': '2020-02-01',
  '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001',
  '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이미경(capital);',
  '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '한국경제',
  '원본주소': 'https://www.hankyung.com/society/article/2020020121817',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002',
  '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '김봄이',
  '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일신문',
  '원본주소': 'https://news.imaeil.com/Society/2020020109431879372',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'}]

In [7]:
print(len(data))
print(data[0])
print('제목-->', data[0]['제목'])
print('본문-->', data[0]['본문'])

1000
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '당직자공용 기자', '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '헤럴드경제', '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027', '일자': '2020-02-01', '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001', '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코,추가,환자,확진'}
제목--> [속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어
본문--> [헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews

In [8]:
for one in data:
    print(one)

{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '당직자공용 기자', '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '헤럴드경제', '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027', '일자': '2020-02-01', '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001', '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코,추가,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이상규', '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일경제', '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020', '일자': '2020-02-01', '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001', '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '접촉자,신종코,감시,확진,검사,속보'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '황재희', '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아주경제', '원본주소': 'http://www.ajunews.com/view/20200201134957462', '일자': '2020-02-01', '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001', '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이미경(capital);', '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '한국경제', '원본주소': 'https://www.hankyung.com/society/article/2020020121817', '일자': '2020-02-01', '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002', '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김봄이', '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일신문', '원본주소': 'https://news.imaeil.com/Society/2020020109431879372', '일자': '2020-02-01', '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001', '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코,추가,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이정환2 기자', '본문': '[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '헤럴드경제', '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000068', '일자': '2020-02-01', '제목': '[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001', '키워드': '신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '접촉자,신종코,감시,확진,검사'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이상규', '본문': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일경제', '원본주소': 'http://news.mk.co.kr/newsRead.php?no=103663&year=2020', '일자': '2020-02-01', '제목': '[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001', '키워드': '신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코,추가,환자,속보,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '전동혁', '본문': '◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': 'MBC', '원본주소': 'https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html', '일자': '2020-02-01', '제목': "2차·3차 감염에도 '슈퍼 전파자'는 없다?", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001', '키워드': '2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '조현의', '본문': '[아시아경제 조현의 기자]  조현의 기자 honey', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아시아경제', '원본주소': 'http:www.asiae.co.kr/article/2020020109535883286', '일자': '2020-02-01', '제목': "[속보] '신종 코로나' 환자 1명 추가…모두 12명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001', '키워드': '신종,코로나,추가,환자,12명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,환자,추가,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': None, '본문': "'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '한국일보', '원본주소': None, '일자': '2020-02-02', '제목': "[속보] '신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001', '키워드': '감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나바이러스,감염증,추가,신종,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '배성훈', '본문': "'신종코로나' 확진환자 3명 추가…국내 총 15명", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일신문', '원본주소': 'https://news.imaeil.com/Society/2020020209591605175', '일자': '2020-02-02', '제목': "[속보] '신종코로나' 확진환자 3명 추가…국내 총 15명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200202100031001', '키워드': '신종코,추가,확진,환자,15명,신종코,추가,확진,환자,15명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코,추가,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이종호 기자', '본문': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중”', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울경제', '원본주소': 'http://www.sedaily.com/NewsView/1YYS34Z0O3', '일자': '2020-02-03', '제목': '질본 “국내 신종코로나 환자 접촉자 총 913명…모니터링 중 (속보)', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203140915001', '키워드': '질본,913명,모니터링,속보,질본,913명,모니터링', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '질본,코로나,접촉자,환자,모니터링,속보,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '조현의', '본문': '[아시아경제 조현의 기자]  조현의 기자 honey', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아시아경제', '원본주소': 'http:www.asiae.co.kr/article/2020020314022654591', '일자': '2020-02-03', '제목': '[속보] 신종 코로나 추가 확진환자 없어…총 15명', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203140309001', '키워드': '신종,코로,추가,확진,환자,15명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,추가,환자,확진,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '우영탁 기자', '본문': '[속보] 2번 환자 유전자증폭검사, 증상 모두 완쾌...퇴원 검토', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울경제', '원본주소': 'http://www.sedaily.com/NewsView/1YYS2DNUZ9', '일자': '2020-02-03', '제목': '[속보] 신종 코로나 2번 환자 유전자증폭검사 음성, 증상 완쾌...퇴원 검토 중', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200203144537001', '키워드': '신종,코로나,환자,유전자,증폭,검사,음성,증상,완쾌,퇴원,검토,속보,유전자증폭검사,환자,유전자,증폭,검사,증상,완쾌,퇴원,검토', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,유전자증폭검사,유전자,음성,환자,증상,검사,퇴원,검토,완쾌,증폭,속보,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '조현의', '본문': '[아시아경제 조현의 기자]  조현의 기자 honey', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아시아경제', '원본주소': 'http:www.asiae.co.kr/article/2020020314113030951', '일자': '2020-02-03', '제목': "[속보] '신종 코로나' 환자 접촉자 총 913명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203141149001', '키워드': '신종,코로나,환자,접촉자,913명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,접촉자,환자,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '문혜원', '본문': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제  문혜원 기자 hmoon3', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아시아경제', '원본주소': 'http:www.asiae.co.kr/article/2020020316544660519', '일자': '2020-02-03', '제목': '[속보]신종 코로나 1번 환자 접촉자 45명 이날 0시 감시 해제', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200203165715001', '키워드': '신종,코로,환자,접촉자,이날,감시,해제,속보,신종,코로,환자,접촉자,이날,감시,해제', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '접촉자,코로,이날,환자,해제,감시,신종,속보'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김영선 기자', '본문': '김영선 기자 ys8584', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '국민일보', '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014198768&code=61121111&cp=kd', '일자': '2020-02-04', '제목': '[속보]신종 코로나 1명 추가 확진…총 16명 환자 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200204110332001', '키워드': '신종,코로,확진,추가,발생,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,추가,환자,발생,확진,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '정종훈(sakehoon)', '본문': '[속보] 신종 코로나 기존 환자 15명 상태 안정적', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '중앙일보', '원본주소': 'https://news.joins.com/article/olink/23291997', '일자': '2020-02-04', '제목': '[속보] 신종 코로나 기존 환자 15명 상태 안정적', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100901.20200204135652001', '키워드': '신종,코로,환자,상태,안정적,속보,신종,코로,환자,상태,안정적', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,환자,안정적,상태,신종,속보'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '류영상', '본문': '[디지털뉴스국 류영상 기자]', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일경제', '원본주소': 'http://news.mk.co.kr/newsRead.php?no=112550&year=2020', '일자': '2020-02-04', '제목': '[속보] `신종코로나` 16번째 확진환자 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200204110312001', '키워드': '신종코,16번,확진,환자,발생', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '16번,신종코,발생,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '황재희', '본문': '[사진=연합뉴스]  신종 코로나바이러스 감염증 확진자가 4일 1명이 추가돼 총 16명으로 늘어났다. 이들과 접촉한 사람은 총 1318명으로 확인됐다. 현재 확진 여부 검사를 실시 중인 사람은 129명이다.   황재희 기자 jhhwang', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아주경제', '원본주소': 'http://www.ajunews.com/view/20200204135428479', '일자': '2020-02-04', '제목': '[속보] 신종 코로나 확진자 16명 접촉자 1318명…129명 검사 중', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200204135754001', '키워드': '신종,코로,확진자,접촉자,129명,검사,신종,코로나바이러스,감염증,확진자,추가,16명,접촉,사람,1318명,확인,검사,확진,여부,사람,129명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '확진자,접촉자,코로나바이러스,감염증,코로,신종,사람,검사,확진,여부,추가,확인,접촉'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': None, '본문': '전 세계를 공포로 몰아넣고 있는 신종 코로나바이러스 감염증(신종 코로나). 무증상 상태에서도 감염이 발생할 수 있는 것으로 알려져 공포심이 더욱 커지고 있다. 국내에서도 빠르게 확진자가 증가하고 있는 가운데 신종 코로나 예방법은 무엇인지 자세히 알아본다.', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '동아일보', '원본주소': 'http://www.donga.com/news/article/all/20200204/99522244/1', '일자': '2020-02-04', '제목': '[오늘의 채널A]신종 코로나 예방법', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100401.20200204030254003', '키워드': '신종,코로,예방법,행복,4일,8시,세계,공포,감염증,신종,코로나바이러스,신종,코로나,상태,감염,발생,공포심,확진자,증가,코로,신종,예방법', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '예방법,코로,공포심,확진자,코로나,코로나바이러스,감염증,신종,상태,발생,증가,세계,감염,행복,공포'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '홍지예', '본문': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '중부일보', '원본주소': 'www.joongboo.com/news/articleView.html?idxno=363397074', '일자': '2020-02-05', '제목': "[속보] '신종 코로나' 확진환자 2명 추가…국내 총 18명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01400501.20200205092214001', '키워드': '신종,코로나,추가,확진,환자,18명,속보,신종,코로나,추가,확진,환자,18명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,추가,속보,환자,신종,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '유현석', '본문': '[아시아경제 유현석 기자]  유현석 기자 guspower', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아시아경제', '원본주소': 'http:www.asiae.co.kr/article/2020020519453821856', '일자': '2020-02-05', '제목': "[속보]'신종 코로나' 19번째 국내 확진환자 발생", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200205194643001', '키워드': '신종,코로나,19번,발생,확진,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,19번,발생,확진,신종,환자'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이상규', '본문': '[디지털뉴스국 이상규 기자]', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일경제', '원본주소': 'http://news.mk.co.kr/newsRead.php?no=117428&year=2020', '일자': '2020-02-05', '제목': '[속보] 신종코로나 검사 하루 160여건…7일부터 2000건 가능해져', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200205111530001', '키워드': '신종,코로나,검사,하루,7일,가능', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,검사,하루,가능,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김민호', '본문': '자세한 내용 이어집니다 김민호 기자 kmh', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '한국일보', '원본주소': None, '일자': '2020-02-05', '제목': '[속보] 신종 코로나, 국내 19번째 환자 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200205050514001', '키워드': '신종,코로나,환자,발생', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,환자,신종,발생'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '정현용', '본문': '신종코로나 19번째 확진환자 발생 정현용 기자 junghy77', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울신문', '원본주소': 'http://www.seoul.co.kr/news/newsView.php?id=20200205500168', '일자': '2020-02-05', '제목': '[속보] 신종코로나 19번째 확진환자 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100611.20200205194759001', '키워드': '신종코로,19번,확진,환자,발생,신종코로,19번,확진,환자,발생', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,19번,신종코로,발생,신종,환자,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김봄이', '본문': "'신종코로나' 확진환자 2명 추가…확진자 18명으로 늘어", '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일신문', '원본주소': 'https://news.imaeil.com/Society/2020020509232224944', '일자': '2020-02-05', '제목': "[속보] '신종코로나' 확진자 2명 추가…국내 총 18명", '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200205092434001', '키워드': '신종코,추가,확진자,18명,신종코,추가,확진,환자,확진자,18명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '확진자,신종코,추가,확진,환자'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김영선 기자', '본문': '김영선 기자 ys8584', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '국민일보', '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014205933&code=61121111&cp=kd', '일자': '2020-02-05', '제목': '[속보]신종 코로나 환자 1명 추가 발생…총 19명 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205194340001', '키워드': '신종,코로,환자,추가,발생,발생', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,환자,발생,추가,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '김영선 기자', '본문': '김영선 기자 ys8584', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '국민일보', '원본주소': 'http://news.kmib.co.kr/article/view.asp?arcid=0014203265&code=61121111&cp=kd', '일자': '2020-02-05', '제목': '[속보]신종 코로나 확진자 2명 추가…총 18명 환자 발생', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01100201.20200205110206002', '키워드': '신종,코로,추가,확진자,발생,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '확진자,코로,환자,발생,추가,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '송종호', '본문': '[사진=연합뉴스 제공]   신종코로나 2번 환자 오늘 퇴원 송종호 기자 sunshine', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '아주경제', '원본주소': 'http://www.ajunews.com/view/20200205133702465', '일자': '2020-02-05', '제목': '[?속보] 신종코로나 2번 환자 오늘 퇴원', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200205134343001', '키워드': '환자,퇴원,신종,코로나,환자,환자,퇴원,신종,코로나,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,환자,신종,퇴원'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '우영탁 기자', '본문': '[속보] 신종코로나 2번 환자 오늘 퇴원', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울경제', '원본주소': 'http://www.sedaily.com/NewsView/1YYSZEKHH6', '일자': '2020-02-05', '제목': '[속보] 신종코로나 2번 환자 오늘 퇴원', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205133301001', '키워드': '환자,퇴원,신종,코로나,환자,속보,환자,퇴원,신종,코로나,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로나,환자,신종,퇴원,속보'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '우영탁 기자', '본문': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울경제', '원본주소': 'http://www.sedaily.com/NewsView/1YYSZAF0RM', '일자': '2020-02-05', '제목': '[속보] 현재 신종 코로나 하루 진단 가능 환자 160명', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200205110416001', '키워드': '신종,코로,160명,하루,진단,가능,환자,속보,신종,코로,160명,하루,진단,가능,환자', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,하루,환자,신종,속보,가능,진단'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '우영탁 기자', '본문': '[속보] 첫번재 환자 상태 호전으로 퇴원', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '서울경제', '원본주소': 'http://www.sedaily.com/NewsView/1YYTG1JJR5', '일자': '2020-02-06', '제목': '[속보] 신종 코로나 첫번재 환자 상태 호전으로 오늘 퇴원', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100311.20200206135226001', '키워드': '신종,코로,번재,환자,상태,호전,퇴원,속보,번재,환자,상태,호전,퇴원', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '번재,코로,호전,상태,퇴원,환자,속보,신종'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '이상규', '본문': '[속보] 신종코로나 확진환자 4명 추가…국내 총 23명 [디지털뉴스국 이상규 기자]', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '매일경제', '원본주소': 'http://news.mk.co.kr/newsRead.php?no=121199&year=2020', '일자': '2020-02-06', '제목': '[속보] 신종코로나 확진환자 4명 추가…국내 총 23명', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200206080807001', '키워드': '신종코로,추가,확진,환자,23명,속보,신종코로,추가,확진,환자,23명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '신종코로,코로,추가,속보,환자,신종,확진'}
{'개체명(기업기관)': None, '개체명(인물)': None, '개체명(지역)': None, '기고자': '손인규 기자', '본문': 'ikson', '사건_사고 분류1': None, '사건_사고 분류2': None, '사건_사고 분류3': None, '언론사': '헤럴드경제', '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200206000039', '일자': '2020-02-06', '제목': '[속보] 신종코로나 확진환자 4명 추가…총 23명', '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200206081018001', '키워드': '신종코로,추가,확진,환자,23명', '통합 분류1': '사회>의료_건강', '통합 분류2': None, '통합 분류3': None, '특성추출': '코로,신종코로,추가,신종,환자,확진'}

In [9]:
with open('covid-sub-data-gokr.json', 'wb') as fp:
    pickle.dump(data, fp)

In [10]:
with open('covid-sub-data-gokr.json', 'rb') as fp:
    json_sub_data = pickle.load(fp)
json_sub_data[:2]

[{'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '당직자공용 기자',
  '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '헤럴드경제',
  '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이상규',
  '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일경제',
  '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '일자': '2020-02-01',
  '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
  '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '접촉자,신종코,감시,확진,검사,속보'}]

In [11]:
import pandas as pd
import numpy as np

In [12]:
df_test = pd.DataFrame(json_sub_data)
df_test

,개체명(기업기관),개체명(인물),개체명(지역),기고자,본문,사건_사고 분류1,사건_사고 분류2,사건_사고 분류3,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,통합 분류2,통합 분류3,특성추출
0,None,None,None,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,None,None,None,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,None,None,"신종코,추가,환자,확진"
1,None,None,None,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,None,None,None,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,None,None,"접촉자,신종코,감시,확진,검사,속보"
2,None,None,None,황재희,[그래픽=연합뉴스] 신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으...,None,None,None,아주경제,http://www.ajunews.com/view/20200201134957462,2020-02-01,[속보] 신종 코로나 확진자 12명…70명 검사 중,http://www.bigkinds.or.kr/news/newsDetailView....,"신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검...",사회>의료_건강,None,None,"확진자,코로나바이러스,코로,검사,신종,확인,사람"
3,None,None,None,이미경(capital);,[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명 이미경 한경닷컴 기자...,None,None,None,한국경제,https://www.hankyung.com/society/article/20200...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명",사회>의료_건강,None,None,"확진환자,1명,6명,신종코,추가,환자,확진,속보,하루"
4,None,None,None,김봄이,'신종코로나' 확진환자 1명 추가…국내 총 12명,None,None,None,매일신문,https://news.imaeil.com/Society/20200201094318...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명",사회>의료_건강,None,None,"신종코,추가,환자,확진"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,정부세종청사 보건복지부 중앙사고수습본부 행정안전부 중수본 질병관리본부,None,None,박세원 기자,중앙사고수습본부(중수본)가 6일 신종 코로나바이러스 감염증(신종 코로나) 확진자 동...,None,None,None,국민일보,http://news.kmib.co.kr/article/view.asp?arcid=...,2020-02-06,"중수본 “동선 공개 늦다? 당사자 기억 의존 NO, 모든 기록 확인”",http://www.bigkinds.or.kr/news/newsDetailView....,"공개,중수본,동선,의존,당사자,기억,의존,기록,확인,지자체,공개,정보,독자,혼선,협...",사회>사회일반,None,None,"지자체,확진자,중수본,질본,당사자,본부장,브리핑실,감염병,감염증,주민들,코로나,김강..."
996,질병관리본부 충남대병원 코젠바이오텍 식약처장,None,None,선정화 기자,[충청투데이 선정화 기자] 충남대병원는 오는 7일부터 신종 코로나바이러스 감염증 신...,None,None,None,충청투데이,http://www.cctoday.co.kr/news/articleView.html...,2020-02-06,"충남대병원, 7일부터 신종 코로나바이러스 신속검사 실시",http://www.bigkinds.or.kr/news/newsDetailView....,"충남대병원,7일,신속검사,신종,코로나바이러스,신속,검사,충남대병원,7일,신종,코로나...",사회>사회일반,None,None,"충남대병원,신속검사,코로나바이러스,유전자,실시간,진단시약,감염증,코젠바이오텍개발,질..."
997,인제군문화재단 EBS,None,None,김보경,【인제】신종 코로나바이러스 확산 우려로 오는 19일에 예정됐던 ..`EBS 모여라 ...,None,None,None,강원일보,http://www.kwnews.co.kr/nView.asp?s=501&aid=22...,2020-02-07,[인제]신종 코로나 확산 우려 `모여라 딩동댕' 연기,http://www.bigkinds.or.kr/news/newsDetailView....,"신종,코로,확산,연기,확산,신종,코로나바이러스,19일,예정,EBS,공개방송,연기,연...",사회>사회일반,None,None,"공개방송,코로나바이러스,코로,출연진들,출연진,개별적,관객층,인제군문화재단,ebs,신..."
998,파주시,None,None,박상돈,파주시는 지난 3일부터 6일까지 관내 환경기초시설을 대상으로 해빙기 대비 안전 점검...,None,None,None,중부일보,www.joongboo.com/news/articleView.html?idxno=3...,2020-02-07,"[e파주소식] 따뜻한 겨울, 변화된 대응 市, 환경기초시설 해빙기 대비 안전점검",http://www.bigkinds.or.kr/news/newsDetailView....,"겨울,변화,대응,환경기초,시설,해빙기,대비,안전,점검,파주시,3일,6일,관내,환경기...",사회>사회일반,None,None,"해빙기,파주시,평균기온,안전점검,김관진,코로나바이러스,위험요소,사업장,파주시청이번,..."
999,정부 주택산업연구원,None,None,김현우,"신종 코로나바이러스 감염증이 주택공급 위축 우려가 있지만, 단기적으로는 영향이 크지...",None,None,None,YTN,https://www.ytn.co.kr/_ln/0102_202002071539372446,2020-02-07,신종코로나로 주택공급 위축 우려...단기 영향 크지 않아,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코로나,주택,공급,위축,단기,영향,감염증,신종,코로나바이러스,주택,공급,위축,단...",사회>사회일반,None,None,"연구원,코로나바이러스,사스,주택구매,장기화,메르스,주택산업연구원,감염증,코로나,신종..."

In [13]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   개체명(기업기관)  574 non-null    object
 1   개체명(인물)    0 non-null      object
 2   개체명(지역)    0 non-null      object
 3   기고자        939 non-null    object
 4   본문         1000 non-null   object
 5   사건_사고 분류1  0 non-null      object
 6   사건_사고 분류2  0 non-null      object
 7   사건_사고 분류3  0 non-null      object
 8   언론사        1000 non-null   object
 9   원본주소       955 non-null    object
 10  일자         1000 non-null   object
 11  제목         1000 non-null   object
 12  주소         1000 non-null   object
 13  키워드        1000 non-null   object
 14  통합 분류1     791 non-null    object
 15  통합 분류2     0 non-null      object
 16  통합 분류3     0 non-null      object
 17  특성추출       1000 non-null   object
dtypes: object(18)
memory usage: 140.8+ KB

In [14]:
df_test.shape

(1000, 18)

In [ ]:
df_test.drop(columns=['개체명(기업기관)','개체명(인물)','개체명(지역)',
                      '사건_사고 분류1','사건_사고 분류2','사건_사고 분류3',
                      '통합 분류2','통합 분류3'],
                     inplace=True
            )
df_test[:2]

,기고자,본문,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,특성추출
0,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,"신종코,추가,환자,확진"
1,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,"접촉자,신종코,감시,확진,검사,속보"

In [15]:
df_test['기고자'][:5]

0         당직자공용 기자
1              이상규
2              황재희
3    이미경(capital);
4              김봄이
Name: 기고자, dtype: object

In [16]:
df_test['본문'][:5]

0    [헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...
1    [속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...
2    [그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으...
3    [속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자...
4                          '신종코로나' 확진환자 1명 추가…국내 총 12명
Name: 본문, dtype: object