In [2]:
import requests #파이썬에서 http통신을 할 수 있는 최근 라이브러리

In [10]:
# 주소?query=자동차
# http(header+body)
# http - 검색(get, header에 요청한 주소+전달값)

# http header에는 보통 인증정보 + 받을 데이터 형식 지정
header_data= {
    'accept': 'application/json',
    'Authorization': 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg==',
}

param_data = (
    ('page', '1'),
    ('perPage', '10'),
    ('serviceKey', 'VXgWV/f5wELzapZjJF7FEqqtFhPbNA8KBIWia3SXOCvY+CXEUok1DhybfbP4USE/g2b/QYT62C2mw3zcSWj2pg=='),
)

url = 'https://api.odcloud.kr/api/15069309/v1/uddi:973ad0df-617a-4565-8e82-8ea7869e75d4'

response = requests.get(url, headers=header_data, params=param_data) 
response #response(http header+body, header(status, message))

In [26]:
json_data = response.text
#http의 body에 온 데이터를 json형태로 저장해라!
#python에서는 {키:값}형태가 딕셔너리(dict)형태로 저장함.
json_data

'{"currentCount":10,"data":[{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"당직자공용 기자","본문":"[헤럴드경제] \'신종코로나\' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"헤럴드경제","원본주소":"http://biz.heraldcorp.com/view.php?ud=20200201000027","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가…12명으로 늘어","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001","키워드":"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이상규","본문":"[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일경제","원본주소":"http://news.mk.co.kr/newsRead.php?no=104142\\u0026year=2020","일자":"2020-02-01","제목":"[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001","키워드":"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"접촉자,신종코,감시,확진,검사,속보"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"황재희","본문":"[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"아주경제","원본주소":"http://www.ajunews.com/view/20200201134957462","일자":"2020-02-01","제목":"[속보] 신종 코로나 확진자 12명…70명 검사 중","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001","키워드":"신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"확진자,코로나바이러스,코로,검사,신종,확인,사람"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이미경(capital);","본문":"[속보] \'신종코로나\' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"한국경제","원본주소":"https://www.hankyung.com/society/article/2020020121817","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002","키워드":"신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"확진환자,1명,6명,신종코,추가,환자,확진,속보,하루"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"김봄이","본문":"\'신종코로나\' 확진환자 1명 추가…국내 총 12명","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일신문","원본주소":"https://news.imaeil.com/Society/2020020109431879372","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가…국내 총 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001","키워드":"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이정환2 기자","본문":"[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"헤럴드경제","원본주소":"http://biz.heraldcorp.com/view.php?ud=20200201000068","일자":"2020-02-01","제목":"[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001","키워드":"신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"접촉자,신종코,감시,확진,검사"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이상규","본문":"[속보] \'신종코로나\' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일경제","원본주소":"http://news.mk.co.kr/newsRead.php?no=103663\\u0026year=2020","일자":"2020-02-01","제목":"[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001","키워드":"신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,속보,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"전동혁","본문":"◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"MBC","원본주소":"https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html","일자":"2020-02-01","제목":"2차·3차 감염에도 \'슈퍼 전파자\'는 없다?","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001","키워드":"2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"조현의","본문":"[아시아경제 조현의 기자]  조현의 기자 honey","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"아시아경제","원본주소":"http:www.asiae.co.kr/article/2020020109535883286","일자":"2020-02-01","제목":"[속보] \'신종 코로나\' 환자 1명 추가…모두 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001","키워드":"신종,코로나,추가,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"코로나,환자,추가,신종"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":null,"본문":"\'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"한국일보","원본주소":null,"일자":"2020-02-02","제목":"[속보] \'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001","키워드":"감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"코로나바이러스,감염증,추가,신종,환자,확진"}],"matchCount":108218,"page":1,"perPage":10,"totalCount":108218}\n'

In [44]:
json_data = response.json()
#http의 body에 온 데이터를 json형태로 저장해라!
#python에서는 {키:값}형태가 딕셔너리(dict)형태로 저장함.
json_data

{'currentCount': 10,
 'data': [{'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '당직자공용 기자',
   '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사,속보'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '황재희',
   '본문': '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아주경제',
   '원본주소': 'http://www.ajunews.com/view/20200201134957462',
   '일자': '2020-02-01',
   '제목': '[속보] 신종 코로나 확진자 12명…70명 검사 중',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001',
   '키워드': '신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진자,코로나바이러스,코로,검사,신종,확인,사람'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이미경(capital);',
   '본문': "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국경제',
   '원본주소': 'https://www.hankyung.com/society/article/2020020121817',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002',
   '키워드': '신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '확진환자,1명,6명,신종코,추가,환자,확진,속보,하루'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '김봄이',
   '본문': "'신종코로나' 확진환자 1명 추가…국내 총 12명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일신문',
   '원본주소': 'https://news.imaeil.com/Society/2020020109431879372',
   '일자': '2020-02-01',
   '제목': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001',
   '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이정환2 기자',
   '본문': '[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '헤럴드경제',
   '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000068',
   '일자': '2020-02-01',
   '제목': '[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001',
   '키워드': '신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '접촉자,신종코,감시,확진,검사'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '이상규',
   '본문': "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '매일경제',
   '원본주소': 'http://news.mk.co.kr/newsRead.php?no=103663&year=2020',
   '일자': '2020-02-01',
   '제목': '[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명',
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001',
   '키워드': '신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '신종코,추가,환자,속보,확진'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '전동혁',
   '본문': '◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': 'MBC',
   '원본주소': 'https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html',
   '일자': '2020-02-01',
   '제목': "2차·3차 감염에도 '슈퍼 전파자'는 없다?",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001',
   '키워드': '2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': '조현의',
   '본문': '[아시아경제 조현의 기자]  조현의 기자 honey',
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '아시아경제',
   '원본주소': 'http:www.asiae.co.kr/article/2020020109535883286',
   '일자': '2020-02-01',
   '제목': "[속보] '신종 코로나' 환자 1명 추가…모두 12명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001',
   '키워드': '신종,코로나,추가,환자,12명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나,환자,추가,신종'},
  {'개체명(기업기관)': None,
   '개체명(인물)': None,
   '개체명(지역)': None,
   '기고자': None,
   '본문': "'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '사건_사고 분류1': None,
   '사건_사고 분류2': None,
   '사건_사고 분류3': None,
   '언론사': '한국일보',
   '원본주소': None,
   '일자': '2020-02-02',
   '제목': "[속보] '신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명",
   '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001',
   '키워드': '감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명',
   '통합 분류1': '사회>의료_건강',
   '통합 분류2': None,
   '통합 분류3': None,
   '특성추출': '코로나바이러스,감염증,추가,신종,환자,확진'}],
 'matchCount': 108218,
 'page': 1,
 'perPage': 10,
 'totalCount': 108218}

In [52]:
json_data2 = response.text #http의 body에 있는 것 그대로 꺼내오겠음.
# json 형태의 str이 들어있음.
json_data2

'{"currentCount":10,"data":[{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"당직자공용 기자","본문":"[헤럴드경제] \'신종코로나\' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"헤럴드경제","원본주소":"http://biz.heraldcorp.com/view.php?ud=20200201000027","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가…12명으로 늘어","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001","키워드":"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이상규","본문":"[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일경제","원본주소":"http://news.mk.co.kr/newsRead.php?no=104142\\u0026year=2020","일자":"2020-02-01","제목":"[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001","키워드":"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"접촉자,신종코,감시,확진,검사,속보"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"황재희","본문":"[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"아주경제","원본주소":"http://www.ajunews.com/view/20200201134957462","일자":"2020-02-01","제목":"[속보] 신종 코로나 확진자 12명…70명 검사 중","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001","키워드":"신종,코로,확진자,70명,검사,확진자,신종,코로나바이러스,1일,2시,12명,확인,검사,사람,70명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"확진자,코로나바이러스,코로,검사,신종,확인,사람"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이미경(capital);","본문":"[속보] \'신종코로나\' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"한국경제","원본주소":"https://www.hankyung.com/society/article/2020020121817","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002","키워드":"신종코,추가,확진,환자,12명,하루,6명,속보,신종코,확진환자,1명,추가,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"확진환자,1명,6명,신종코,추가,환자,확진,속보,하루"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"김봄이","본문":"\'신종코로나\' 확진환자 1명 추가…국내 총 12명","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일신문","원본주소":"https://news.imaeil.com/Society/2020020109431879372","일자":"2020-02-01","제목":"[속보] \'신종코로나\' 확진환자 1명 추가…국내 총 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001","키워드":"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이정환2 기자","본문":"[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"헤럴드경제","원본주소":"http://biz.heraldcorp.com/view.php?ud=20200201000068","일자":"2020-02-01","제목":"[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001","키워드":"신종코,확진,70명,검사,접촉자,감시,신종코,확진,70명,검사,접촉자,감시","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"접촉자,신종코,감시,확진,검사"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"이상규","본문":"[속보] \'신종코로나\' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"매일경제","원본주소":"http://news.mk.co.kr/newsRead.php?no=103663\\u0026year=2020","일자":"2020-02-01","제목":"[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001","키워드":"신종코,추가,확진,환자,12명,속보,신종코,추가,확진,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"신종코,추가,환자,속보,확진"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"전동혁","본문":"◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"MBC","원본주소":"https://imnews.imbc.com/replay/2020/nwtoday/article/5656267_32531.html","일자":"2020-02-01","제목":"2차·3차 감염에도 \'슈퍼 전파자\'는 없다?","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001","키워드":"2차,3차,감염,슈퍼,전파자,앵커,감염,감염자,확진자,슈퍼,전파자,전문가들,가능성,대비,전동혁,취재,리포트,발생,중동호흡기증후군,메르스,사태,186명,감염자,확인,보건,당국,5명,역학,조사,결과,감염자,환자,82%,153명,감염,전파력,감염자,슈퍼,전파자,기침,호흡기,증상,특징,보건,당국,코로,신종,확산,양상,슈퍼,전파자,표현,설명,슈퍼전파자,면역력,환자,병원,사람,전염,슈퍼,전파,이벤트,정은경,중앙방역대책본부장,슈퍼,전파자,기준,밀폐,의료기관,노출,경우들,슈퍼,전파,이벤트,단언,일각,지적,확진,환자,밀접,접촉,가능,공공이용시설,병원,극장,이용,신종코로나,잠복기,최대,가량,증상,만큼,차후,환자,의료,관계자,사례,전파,슈퍼,증거,가능성,차원,사전,예방,대비책,검토,얘기,보건,당국,지역,감염,제한,범위,가족,지인,사이,전파,위험도,입장,정은경,중앙방역대책본부장,감염원,환자들,발견,광범위,환자,발생,증거들,위험도,평가,판단,보건,당국,역학조사관,판단,기준,밀접,접촉자,분류,관리,지역사회,신종코로나,전파,차단,평소,준수,기침,예절,감염병,예방,당부","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"감염자,전파자,호흡기,위험도,전동혁,관계자,정은경,만큼,신종코로나,본부장,가능성,코로나,환자들,2차,3차,메르스,중앙방역,경우들,대비책,중앙방역대책본부장,의료기관,증후군,잠복기,전문가,공공이용시설,감염병"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":"조현의","본문":"[아시아경제 조현의 기자]  조현의 기자 honey","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"아시아경제","원본주소":"http:www.asiae.co.kr/article/2020020109535883286","일자":"2020-02-01","제목":"[속보] \'신종 코로나\' 환자 1명 추가…모두 12명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001","키워드":"신종,코로나,추가,환자,12명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"코로나,환자,추가,신종"},{"개체명(기업기관)":null,"개체명(인물)":null,"개체명(지역)":null,"기고자":null,"본문":"\'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명","사건_사고 분류1":null,"사건_사고 분류2":null,"사건_사고 분류3":null,"언론사":"한국일보","원본주소":null,"일자":"2020-02-02","제목":"[속보] \'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명","주소":"http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001","키워드":"감염증,신종,코로나바이러스,추가,확진,환자,15명,감염증,신종,코로나바이러스,추가,확진,환자,15명","통합 분류1":"사회\\u003e의료_건강","통합 분류2":null,"통합 분류3":null,"특성추출":"코로나바이러스,감염증,추가,신종,환자,확진"}],"matchCount":108218,"page":1,"perPage":10,"totalCount":108218}\n'

In [45]:
type(json_data)

dict

In [46]:
import pickle

In [47]:
# 예외처리(try~except)는 외부 자원을 연결할 때
# 외부 자원 : network(openapi, db), file, cpu(thread.sleep())
# 외부 자원연결할 때 파이썬과 외부 자원사이에 연결(stream, 강물)이 만들어짐.
# 스트림이 만들어지면 반드시 없애주어야함. close해주어야함.
# try:
#    file.open(파일명, "r"):
#      print(읽어온 데이터)
#    file.close()
# except:
#    print("문제가 생겼음")

# fp = file.open('covid-gokr.json', 'wb')
# fp.close()

# with라고 써주면 자동으로 close해줌.
with open('covid-gokr.json', 'wb') as fp:
    pickle.dump(json_data, fp)

In [48]:
with open('covid-gokr.json', 'rb') as fp:
    json_read_data = pickle.load(fp)

In [49]:
# json_read_data

In [50]:
json_read_data['currentCount']

10

In [51]:
json_data['data'][:2]

[{'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '당직자공용 기자',
  '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '헤럴드경제',
  '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
  '일자': '2020-02-01',
  '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
  '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '신종코,추가,환자,확진'},
 {'개체명(기업기관)': None,
  '개체명(인물)': None,
  '개체명(지역)': None,
  '기고자': '이상규',
  '본문': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]',
  '사건_사고 분류1': None,
  '사건_사고 분류2': None,
  '사건_사고 분류3': None,
  '언론사': '매일경제',
  '원본주소': 'http://news.mk.co.kr/newsRead.php?no=104142&year=2020',
  '일자': '2020-02-01',
  '제목': '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시',
  '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001',
  '키워드': '신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시',
  '통합 분류1': '사회>의료_건강',
  '통합 분류2': None,
  '통합 분류3': None,
  '특성추출': '접촉자,신종코,감시,확진,검사,속보'}]

In [18]:
data_values = json_data['data'] #data키에 대한 값은 리스트임.
len(data_values)

10

In [19]:
data_values[0]

{'개체명(기업기관)': None,
 '개체명(인물)': None,
 '개체명(지역)': None,
 '기고자': '당직자공용 기자',
 '본문': "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews",
 '사건_사고 분류1': None,
 '사건_사고 분류2': None,
 '사건_사고 분류3': None,
 '언론사': '헤럴드경제',
 '원본주소': 'http://biz.heraldcorp.com/view.php?ud=20200201000027',
 '일자': '2020-02-01',
 '제목': "[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어",
 '주소': 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001',
 '키워드': '신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명',
 '통합 분류1': '사회>의료_건강',
 '통합 분류2': None,
 '통합 분류3': None,
 '특성추출': '신종코,추가,환자,확진'}

In [20]:
type(data_values)

list

In [21]:
one = data_values[0]
one['제목']

"[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어"

In [53]:
data_values[0]['제목']

"[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어"

In [22]:
one['언론사']

'헤럴드경제'

In [24]:
one['일자']

'2020-02-01'

In [54]:
one_row = []
one_row.append(data_values[0]['제목']) # 제목
one_row.append(data_values[0]['본문']) # 본문
one_row.append(data_values[0]['통합 분류1']) # 분야
one_row.append(data_values[0]['일자']) # 일자
one_row.append(data_values[0]['주소']) # 주소
one_row.append(data_values[0]['언론사']) # 언론사

print(one_row)

["[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어", "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews", '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001', '헤럴드경제']

In [55]:
total_row = [] #2차원리스틑 1차원리스트를 모아놓은 것.
#하나의  dict은 하나의 리스트임
#여러개는 [[row],[row],[row]] 2차원 리스트

for no in range(10): #0~9
    one_row = []
    one_row.append(data_values[no]['제목']) # 제목
    one_row.append(data_values[no]['본문']) # 본문
    one_row.append(data_values[no]['통합 분류1']) # 분야
    one_row.append(data_values[no]['일자']) # 일자
    one_row.append(data_values[no]['주소']) # 주소
    one_row.append(data_values[no]['언론사']) # 언론사

    print(one_row)

    total_row.append(one_row)
    
len(total_row)

["[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어", "[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 12명이 됐다.   onlinenews", '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201094636001', '헤럴드경제']
['[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시', '[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털뉴스국 이상규 기자]', '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201142733001', '매일경제']
['[속보] 신종 코로나 확진자 12명…70명 검사 중', '[그래픽=연합뉴스]  신종 코로나바이러스 확진자가 1일 오후 2시 현재 총 12명으로 확인됐다. 현재 검사 중인 사람은 총 70명이다. 황재희 기자 jhhwang', '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100851.20200201135243001', '아주경제']
["[속보] '신종코로나' 확진환자 1명 추가돼 국내 총 12명…하루 새 6명 늘어", "[속보] '신종코로나' 확진환자…1명 추가 국내 총 12명   이미경 한경닷컴 기자 capital 기사제보 및 보도자료 open", '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100601.20200201100004002', '한국경제']
["[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명", "'신종코로나' 확진환자 1명 추가…국내 총 12명", '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01500601.20200201094329001', '매일신문']
['[속보] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시', '[헤럴드경제] 신종코로나 국내 12명 확진·70명은 검사 중…접촉자 465명 감시', '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100701.20200201135936001', '헤럴드경제']
['[속보] `신종코로나` 확진환자 1명 추가…국내 총 12명', "[속보] '신종코로나' 확진환자 1명 추가…국내 총 12명 [디지털뉴스국 이상규 기자]", '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100101.20200201094426001', '매일경제']
["2차·3차 감염에도 '슈퍼 전파자'는 없다?", '◀ 앵커 ..▶ .. ..국내에서 2차 감염에 이어 3차 감염자까지 나오면서 확진자 중에 슈퍼 전파자가 나올 수도 있다는 우려가 커지고 있습니다... .. .. ..전문가들은 모든 가능성을 열어두고 대비해야 한다고 입을 모으고 있습니다... .. .. ..전동혁 기자가 취재했습니다. .. ..◀ 리포트 ..▶ .. ..지난 2015년 발생한 중동호흡기증..', '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=08100201.20200201063326001', 'MBC']
["[속보] '신종 코로나' 환자 1명 추가…모두 12명", '[아시아경제 조현의 기자]  조현의 기자 honey', '사회>의료_건강', '2020-02-01', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=02100801.20200201095406001', '아시아경제']
["[속보] '신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명", "'신종 코로나바이러스 감염증’ 확진환자 3명 추가…국내 총 15명", '사회>의료_건강', '2020-02-02', 'http://www.bigkinds.or.kr/news/newsDetailView.do?newsId=01101101.20200202050115001', '한국일보']

10

In [56]:
import pandas as pd
import numpy as np

In [57]:
with open('covid-sub-data-dic.json', 'wb') as fp:
    pickle.dump(data_values, fp)

In [58]:
with open('covid-sub-data-dic.json', 'rb') as fp:
    json_sub_data_dic = pickle.load(fp)

In [59]:
df_test = pd.DataFrame(json_sub_data_dic) #[dic, dic, dic]
df_test[:2]

,개체명(기업기관),개체명(인물),개체명(지역),기고자,본문,사건_사고 분류1,사건_사고 분류2,사건_사고 분류3,언론사,원본주소,일자,제목,주소,키워드,통합 분류1,통합 분류2,통합 분류3,특성추출
0,None,None,None,당직자공용 기자,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,None,None,None,헤럴드경제,http://biz.heraldcorp.com/view.php?ud=20200201...,2020-02-01,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,추가,확진,환자,12명,신종코,추가,확진,환자,확진,12명",사회>의료_건강,None,None,"신종코,추가,환자,확진"
1,None,None,None,이상규,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,None,None,None,매일경제,http://news.mk.co.kr/newsRead.php?no=104142&ye...,2020-02-01,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,http://www.bigkinds.or.kr/news/newsDetailView....,"신종코,확진,70명,검사,접촉자,감시,속보,신종코,확진,70명,검사,접촉자,감시",사회>의료_건강,None,None,"접촉자,신종코,감시,확진,검사,속보"

In [61]:
df_test2 = pd.DataFrame(
    total_row,
    columns=['제목', '본문', '통합 분류1', '일자', '주소', '언론사']
) 
df_test2.head(2)

,제목,본문,통합 분류1,일자,주소,언론사
0,[속보] '신종코로나' 확진환자 1명 추가…12명으로 늘어,[헤럴드경제] '신종코로나' 확진환자 1명 추가됐다. 이로써 국내 확진환자는 총 1...,사회>의료_건강,2020-02-01,http://www.bigkinds.or.kr/news/newsDetailView....,헤럴드경제
1,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시,[속보] 신종코로나 국내 12명 확진·70명 검사 중…접촉자 465명 감시 [디지털...,사회>의료_건강,2020-02-01,http://www.bigkinds.or.kr/news/newsDetailView....,매일경제